// Fill out your copyright notice in the Description page of Project Settings.


#include "PlayerMade/PlayerCharacter.h"
#include "GameFramework/SpringArmComponent.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "EnhancedInputSubsystems.h"
#include "EnhancedInputComponent.h"
#include "InputAction.h"
#include "PlayerMade/CharacterStatsComponent.h" // ğŸ’¡ [ìˆ˜ì •ë¨] Stats Component í—¤ë” ì¶”ê°€
#include "Components/CapsuleComponent.h" // ğŸ’¡ [ìˆ˜ì •ë¨] ì‚¬ë§ ì‹œ ì¶©ëŒ ë¹„í™œì„±í™”ë¥¼ ìœ„í•´ ì¶”ê°€

// Sets default values
APlayerCharacter::APlayerCharacter()
{
	PrimaryActorTick.bCanEverTick = false;

	// === 1. íƒ‘ë‹¤ìš´ ì¹´ë©”ë¼ ì„¤ì • ===
	CameraBoom = CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraBoom"));
	CameraBoom->SetupAttachment(RootComponent);

	CameraBoom->TargetArmLength = 1500.0f;
	CameraBoom->SetRelativeRotation(FRotator(-120.0f, 0.0f, 0.0f));
	CameraBoom->bUsePawnControlRotation = false;
	CameraBoom->bDoCollisionTest = false;
	CameraBoom->bInheritYaw = false;
	CameraBoom->bInheritRoll = false;

	FollowCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("FollowCamera"));
	FollowCamera->SetupAttachment(CameraBoom, USpringArmComponent::SocketName);

	// ğŸ’¡ [ìˆ˜ì •ë¨] CharacterStatsComponent ìƒì„± ë° ë¶€ì°©
	StatsComponent = CreateDefaultSubobject<UCharacterStatsComponent>(TEXT("StatsComponent"));

	// === 2. ì´ë™ ë° íšŒì „ ì„¤ì • ===
	bUseControllerRotationYaw = false;
	GetCharacterMovement()->bOrientRotationToMovement = true;
	GetCharacterMovement()->RotationRate = FRotator(0.0f, 0.0f, 0.0f);
}

// Called when the game starts or when spawned
void APlayerCharacter::BeginPlay()
{
	Super::BeginPlay();

	if (APlayerController* PlayerController = Cast<APlayerController>(Controller))
	{
		// ë§ˆìš°ìŠ¤ ì»¤ì„œ í‘œì‹œ
		PlayerController->bShowMouseCursor = true;
		PlayerController->DefaultMouseCursor = EMouseCursor::Crosshairs;

		// Enhanced Input Context ì ìš©
		if (UEnhancedInputLocalPlayerSubsystem* Subsystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PlayerController->GetLocalPlayer()))
		{
			if (InputMappingContext)
			{
				Subsystem->AddMappingContext(InputMappingContext, 0);
			}
		}
	}
}

// Called to bind functionality to input
void APlayerCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	// Enhanced Input ë°”ì¸ë”©
	if (UEnhancedInputComponent* EnhancedInputComponent = Cast<UEnhancedInputComponent>(PlayerInputComponent))
	{
		if (MoveAction)
		{
			EnhancedInputComponent->BindAction(MoveAction, ETriggerEvent::Triggered, this, &APlayerCharacter::Move);
		}
	}
}

// Move ì½œë°± í•¨ìˆ˜ (WASD ì²˜ë¦¬)
void APlayerCharacter::Move(const FInputActionValue& Value)
{
	FVector2D MovementVector = Value.Get<FVector2D>();

	if (Controller != nullptr)
	{
		// ì¹´ë©”ë¼ì˜ Yaw íšŒì „ì„ ê¸°ì¤€ìœ¼ë¡œ ë°©í–¥ì„ ê³„ì‚° (íƒ‘ë‹¤ìš´ ì‹œì  ì´ë™)
		// const FRotator Rotation = CameraBoom->GetComponentRotation();
		//const FRotator Rotation = Controller->GetControlRotation();
		//const FRotator YawRotation(0, Rotation.Yaw, 0);

		const FRotator Rotation = Controller->GetControlRotation();
		const FRotator YawRotation(0, Rotation.Yaw, 0);

		const FVector ForwardDirection = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::X);
		const FVector RightDirection = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::Y);

		AddMovementInput(ForwardDirection, MovementVector.Y);
		AddMovementInput(RightDirection, MovementVector.X);

		if (!MovementVector.IsNearlyZero())
		{
			const FVector MoveDir = (ForwardDirection * MovementVector.Y + RightDirection * MovementVector.X).GetSafeNormal();
			SetActorRotation(MoveDir.Rotation());
		}


		//if (!FMath::IsNearlyZero(MovementVector.Y))
		//{
		//	const FVector ForwardDirection = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::X);
		//	AddMovementInput(ForwardDirection, MovementVector.Y);
		//	/*FRotator(0.0f, 0.0f, 0.0f);*/
		//}

		//if (!FMath::IsNearlyZero(MovementVector.X))
		//{
		//	const FVector RightDirection = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::Y);
		//	AddMovementInput(RightDirection, MovementVector.X);
		//}
	}
}

// ğŸ’¡ [ìˆ˜ì •ë¨] ë°ë¯¸ì§€ ì²˜ë¦¬ë¥¼ StatsComponentì— ìœ„ì„
float APlayerCharacter::TakeDamage(float DamageAmount, FDamageEvent const& DamageEvent, AController* EventInstigator, AActor* DamageCauser)
{
	if (!StatsComponent)
	{
		return 0.0f;
	}

	// StatsComponentì˜ ë°ë¯¸ì§€ ì²˜ë¦¬ ë¡œì§ í˜¸ì¶œ
	const float ActualDamage = StatsComponent->TakeDamage(DamageAmount);

	// ì‚¬ë§í–ˆëŠ”ì§€ í™•ì¸í•˜ê³ , ìºë¦­í„°ì˜ ë¬¼ë¦¬ì  ë°˜ì‘ ì²˜ë¦¬
	if (StatsComponent->IsDead())
	{
		PlayerIsDead();
	}

	return ActualDamage;
}

// ğŸ’¡ [ìˆ˜ì •ë¨] PlayerIsDeadëŠ” ì´ì œ ìºë¦­í„°ì˜ ë¬¼ë¦¬ì  ë¹„í™œì„±í™”ë§Œ ë‹´ë‹¹
void APlayerCharacter::PlayerIsDead()
{
	UE_LOG(LogTemp, Error, TEXT("PLAYER IS DEAD! Deactivating input and collision."));

	// 1. ì…ë ¥ ë¹„í™œì„±í™”
	if (APlayerController* PC = Cast<APlayerController>(GetController()))
	{
		DisableInput(PC);
	}

	// 2. ìºë¦­í„° ì¶©ëŒ ë¹„í™œì„±í™”
	if (GetCapsuleComponent())
	{
		GetCapsuleComponent()->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	}
}